stages:
  data ingestion:
    cmd: python src/deepClassifier/pipeline/stage_01_data_ingestion.py
    deps: 
      - src/deepClassifier/pipeline/stage_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages
  
  prepare base_model:
    cmd: python src/deepClassifier/pipeline/stage_02_prepare_base_model.py
    deps: 
      - src/deepClassifier/pipeline/stage_02_prepare_base_model.py
      - artifacts/data_ingestion/PetImages
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model
    
  prepareCallback and training:
    cmd: python src/deepClassifier/pipeline/stage_03_training.py
    deps:
      - src/deepClassifier/pipeline/stage_03_training.py
      - src/deepClassifier/components/prepare_callback.py
      - artifacts/data_ingestion/PetImages
      - artifacts/prepare_base_model
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5